"""Crickium Quest task catalog generated from the supplied 300-task PDF.

Do not hand-edit task definitions here. The PDF is the source of truth for
task IDs, difficulty, titles, descriptions, and Sigil rewards.
"""
from __future__ import annotations

QUEST_TASKS = [{'id': 'D001',
  'difficulty': 'Easy',
  'title': '🏏 Run Forge',
  'description': 'Score 100 total team runs across any number of completed matches.',
  'sigils': 10},
 {'id': 'D002',
  'difficulty': 'Easy',
  'title': '🏏 Run Engine',
  'description': 'Score 150 total team runs across completed matches.',
  'sigils': 10},
 {'id': 'D003',
  'difficulty': 'Easy',
  'title': '🏏 Run Builder',
  'description': 'Score 200 total team runs across completed matches.',
  'sigils': 10},
 {'id': 'D004',
  'difficulty': 'Easy',
  'title': '🔥 Run Surge',
  'description': 'Score 300 total team runs across completed matches.',
  'sigils': 10},
 {'id': 'D005',
  'difficulty': 'Medium',
  'title': '💥 Run Reactor',
  'description': 'Score 500 total team runs across completed matches.',
  'sigils': 20},
 {'id': 'D006',
  'difficulty': 'Hard',
  'title': '⚡ Run Empire',
  'description': 'Score 1,000 total team runs across completed matches.',
  'sigils': 30},
 {'id': 'D007',
  'difficulty': 'Medium',
  'title': '🎯 Pitch-Proof Runs',
  'description': 'Score 200 team runs regardless of the pitch condition.',
  'sigils': 20},
 {'id': 'D008',
  'difficulty': 'Medium',
  'title': '🔥 Run Marathon',
  'description': 'Score 400 team runs across at least three matches.',
  'sigils': 20},
 {'id': 'D009',
  'difficulty': 'Hard',
  'title': '👑 Run Dominion',
  'description': 'Score 750 team runs across the day.',
  'sigils': 30},
 {'id': 'D010',
  'difficulty': 'Hard',
  'title': '🚀 Thousand Club',
  'description': 'Score 1,000 team runs across the day.',
  'sigils': 30},
 {'id': 'D011',
  'difficulty': 'Easy',
  'title': '🏏 Fifty Maker',
  'description': 'Have any player score 50 runs in a match.',
  'sigils': 10},
 {'id': 'D012',
  'difficulty': 'Easy',
  'title': '🔥 Seventy Surge',
  'description': 'Have any player score 75 runs in a match.',
  'sigils': 10},
 {'id': 'D013',
  'difficulty': 'Medium',
  'title': '💯 Century Strike',
  'description': 'Have any player score 100 runs in a match.',
  'sigils': 20},
 {'id': 'D014',
  'difficulty': 'Hard',
  'title': '💥 Big Score',
  'description': 'Have any player score 125 runs in a match.',
  'sigils': 30},
 {'id': 'D015',
  'difficulty': 'Hard',
  'title': '👑 Batting Monarch',
  'description': 'Have any player score 150 runs in a match.',
  'sigils': 30},
 {'id': 'D016',
  'difficulty': 'Medium',
  'title': '🎯 Chase Fifty',
  'description': 'Have any player score 50 runs while chasing.',
  'sigils': 20},
 {'id': 'D017',
  'difficulty': 'Medium',
  'title': '🔥 Chase Century',
  'description': 'Have any player score 100 runs while chasing.',
  'sigils': 20},
 {'id': 'D018',
  'difficulty': 'Hard',
  'title': '⚡ Chase Titan',
  'description': 'Have any player score 125 runs while chasing.',
  'sigils': 30},
 {'id': 'D019',
  'difficulty': 'Medium',
  'title': '🛡️ Defence Fifty',
  'description': 'Have any player score 50 runs while defending a total.',
  'sigils': 20},
 {'id': 'D020',
  'difficulty': 'Hard',
  'title': '👑 Defence Century',
  'description': 'Have any player score 100 runs while defending a total.',
  'sigils': 30},
 {'id': 'D021',
  'difficulty': 'Easy',
  'title': '🏏 Player Runbank',
  'description': 'Any one player must reach 100 combined runs across matches.',
  'sigils': 10},
 {'id': 'D022',
  'difficulty': 'Easy',
  'title': '🔥 Player Runstream',
  'description': 'Any one player must reach 150 combined runs across matches.',
  'sigils': 10},
 {'id': 'D023',
  'difficulty': 'Medium',
  'title': '💥 Player Run Vault',
  'description': 'Any one player must reach 200 combined runs across matches.',
  'sigils': 20},
 {'id': 'D024',
  'difficulty': 'Medium',
  'title': '⚡ Player Run Tower',
  'description': 'Any one player must reach 300 combined runs across matches.',
  'sigils': 20},
 {'id': 'D025',
  'difficulty': 'Hard',
  'title': '👑 Player Run Crown',
  'description': 'Any one player must reach 500 combined runs across matches.',
  'sigils': 30},
 {'id': 'D026',
  'difficulty': 'Hard',
  'title': '🚀 Player Run Legend',
  'description': 'Any one player must reach 700 combined runs across matches.',
  'sigils': 30},
 {'id': 'D027',
  'difficulty': 'Medium',
  'title': '🎯 Chase Runbank',
  'description': 'Any one player must reach 150 combined chase runs.',
  'sigils': 20},
 {'id': 'D028',
  'difficulty': 'Hard',
  'title': '🔥 Chase Run Vault',
  'description': 'Any one player must reach 300 combined chase runs.',
  'sigils': 30},
 {'id': 'D029',
  'difficulty': 'Medium',
  'title': '🛡️ Defence Runbank',
  'description': 'Any one player must reach 150 combined runs while defending.',
  'sigils': 20},
 {'id': 'D030',
  'difficulty': 'Hard',
  'title': '👑 Defence Run Vault',
  'description': 'Any one player must reach 300 combined runs while defending.',
  'sigils': 30},
 {'id': 'D031',
  'difficulty': 'Easy',
  'title': '🔥 Four Hunter',
  'description': 'Hit 5 fours across all completed matches.',
  'sigils': 10},
 {'id': 'D032',
  'difficulty': 'Easy',
  'title': '💥 Boundary Smith',
  'description': 'Hit 10 fours across all completed matches.',
  'sigils': 10},
 {'id': 'D033',
  'difficulty': 'Medium',
  'title': '⚡ Four Machine',
  'description': 'Hit 20 fours across all completed matches.',
  'sigils': 20},
 {'id': 'D034',
  'difficulty': 'Medium',
  'title': '🔥 Six Smith',
  'description': 'Hit 5 sixes across all completed matches.',
  'sigils': 20},
 {'id': 'D035',
  'difficulty': 'Medium',
  'title': '💥 Sixes Hitting Machine',
  'description': 'Hit 10 sixes across all completed matches.',
  'sigils': 20},
 {'id': 'D036',
  'difficulty': 'Hard',
  'title': '👑 Sixes Factory',
  'description': 'Hit 20 sixes across all completed matches.',
  'sigils': 30},
 {'id': 'D037',
  'difficulty': 'Medium',
  'title': '🎯 Player Six Shot',
  'description': 'Have one player hit 3 sixes in a single match.',
  'sigils': 20},
 {'id': 'D038',
  'difficulty': 'Hard',
  'title': '🚀 Six Storm',
  'description': 'Have one player hit 5 sixes in a single match.',
  'sigils': 30},
 {'id': 'D039',
  'difficulty': 'Hard',
  'title': '🔥 Chase Sixes',
  'description': 'Hit 10 sixes while chasing across matches.',
  'sigils': 30},
 {'id': 'D040',
  'difficulty': 'Hard',
  'title': '🛡️ Defence Sixes',
  'description': 'Hit 10 sixes while batting in matches you defend.',
  'sigils': 30},
 {'id': 'D041',
  'difficulty': 'Easy',
  'title': '🎯 Wicket Hunter',
  'description': 'Take 3 wickets across completed matches.',
  'sigils': 10},
 {'id': 'D042',
  'difficulty': 'Medium',
  'title': '🔥 Wicket Forge',
  'description': 'Take 5 wickets across completed matches.',
  'sigils': 20},
 {'id': 'D043',
  'difficulty': 'Medium',
  'title': '💥 Wicket Bank',
  'description': 'Take 10 wickets across completed matches.',
  'sigils': 20},
 {'id': 'D044',
  'difficulty': 'Hard',
  'title': '👑 Wicket Dominion',
  'description': 'Take 20 wickets across completed matches.',
  'sigils': 30},
 {'id': 'D045',
  'difficulty': 'Hard',
  'title': '🚀 Wicket Empire',
  'description': 'Take 30 wickets across completed matches.',
  'sigils': 30},
 {'id': 'D046',
  'difficulty': 'Medium',
  'title': '🎯 Three-Wicket Burst',
  'description': 'Have one player take 3 wickets in a match.',
  'sigils': 20},
 {'id': 'D047',
  'difficulty': 'Hard',
  'title': '🔥 Five-Wicket Master',
  'description': 'Have one player take 5 wickets in a match.',
  'sigils': 30},
 {'id': 'D048',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Hunter',
  'description': 'Take 2 wickets during powerplay overs.',
  'sigils': 20},
 {'id': 'D049',
  'difficulty': 'Medium',
  'title': '💥 Middle Over Snare',
  'description': 'Take 2 wickets during middle overs.',
  'sigils': 20},
 {'id': 'D050',
  'difficulty': 'Hard',
  'title': '👑 Death Over Hunter',
  'description': 'Take 3 wickets during death overs.',
  'sigils': 30},
 {'id': 'D051',
  'difficulty': 'Easy',
  'title': '🟢 Dot Maker',
  'description': 'Deliver 10 dot balls across matches.',
  'sigils': 10},
 {'id': 'D052',
  'difficulty': 'Medium',
  'title': '🎯 Dot Storm',
  'description': 'Deliver 20 dot balls across matches.',
  'sigils': 20},
 {'id': 'D053',
  'difficulty': 'Hard',
  'title': '🔥 Dot Dominion',
  'description': 'Deliver 40 dot balls across matches.',
  'sigils': 30},
 {'id': 'D054',
  'difficulty': 'Medium',
  'title': '🧊 Powerplay Lock',
  'description': 'Complete a powerplay over while conceding 6 or fewer runs.',
  'sigils': 20},
 {'id': 'D055',
  'difficulty': 'Hard',
  'title': '🛡️ Middle Over Lock',
  'description': 'Complete a middle over while conceding 6 or fewer runs.',
  'sigils': 30},
 {'id': 'D056',
  'difficulty': 'Hard',
  'title': '🔥 Death Over Lock',
  'description': 'Complete a death over while conceding 8 or fewer runs.',
  'sigils': 30},
 {'id': 'D057',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Runner',
  'description': 'Score 25 team runs in powerplay overs.',
  'sigils': 20},
 {'id': 'D058',
  'difficulty': 'Medium',
  'title': '🔥 Middle Over Runner',
  'description': 'Score 30 team runs in middle overs.',
  'sigils': 20},
 {'id': 'D059',
  'difficulty': 'Hard',
  'title': '💥 Death Over Runner',
  'description': 'Score 30 team runs in death overs.',
  'sigils': 30},
 {'id': 'D060',
  'difficulty': 'Hard',
  'title': '👑 Death Over Burst',
  'description': 'Score 40 team runs in death overs.',
  'sigils': 30},
 {'id': 'D061',
  'difficulty': 'Easy',
  'title': '🏃 Chase Starter',
  'description': 'Win 1 match while chasing.',
  'sigils': 10},
 {'id': 'D062',
  'difficulty': 'Medium',
  'title': '🔥 Chase Master',
  'description': 'Win 2 matches while chasing.',
  'sigils': 20},
 {'id': 'D063',
  'difficulty': 'Hard',
  'title': '👑 Chase King',
  'description': 'Win 3 matches while chasing.',
  'sigils': 30},
 {'id': 'D064',
  'difficulty': 'Hard',
  'title': '⚡ Late Chase',
  'description': 'Win a chase after reaching the final five overs.',
  'sigils': 30},
 {'id': 'D065',
  'difficulty': 'Medium',
  'title': '🎯 Chase Runs',
  'description': 'Score 100 team runs while chasing across matches.',
  'sigils': 20},
 {'id': 'D066',
  'difficulty': 'Hard',
  'title': '💥 Chase Fifty Pair',
  'description': 'Have any player score 50 while chasing and win the match.',
  'sigils': 30},
 {'id': 'D067',
  'difficulty': 'Hard',
  'title': '💯 Chase Century Win',
  'description': 'Have any player score 100 while chasing and win the match.',
  'sigils': 30},
 {'id': 'D068',
  'difficulty': 'Medium',
  'title': '🛡️ Defence Starter',
  'description': 'Win 1 match while defending a total.',
  'sigils': 20},
 {'id': 'D069',
  'difficulty': 'Hard',
  'title': '🔥 Defence Master',
  'description': 'Win 2 matches while defending a total.',
  'sigils': 30},
 {'id': 'D070',
  'difficulty': 'Hard',
  'title': '👑 Defence King',
  'description': 'Win 3 matches while defending a total.',
  'sigils': 30},
 {'id': 'D071',
  'difficulty': 'Hard',
  'title': '⚡ Defence Wickets',
  'description': 'Take 3 wickets while defending and win the match.',
  'sigils': 30},
 {'id': 'D072',
  'difficulty': 'Hard',
  'title': '🔥 Defence Five',
  'description': 'Take 5 wickets while defending across matches.',
  'sigils': 30},
 {'id': 'D073',
  'difficulty': 'Medium',
  'title': '🎯 Comeback Chase',
  'description': 'Win after trailing at some point during the chase.',
  'sigils': 20},
 {'id': 'D074',
  'difficulty': 'Medium',
  'title': '🛡️ Comeback Defence',
  'description': 'Win after conceding a boundary during the defence.',
  'sigils': 20},
 {'id': 'D075',
  'difficulty': 'Medium',
  'title': '🏏 Match Finisher',
  'description': 'Complete 2 Play Game matches.',
  'sigils': 20},
 {'id': 'D076',
  'difficulty': 'Medium',
  'title': '🔥 IPL Runner',
  'description': 'Complete 1 Play IPL match.',
  'sigils': 20},
 {'id': 'D077', 'difficulty': 'Hard', 'title': '👑 IPL Winner', 'description': 'Win 1 Play IPL match.', 'sigils': 30},
 {'id': 'D078',
  'difficulty': 'Medium',
  'title': '🌍 International Run',
  'description': 'Complete 1 Play International match.',
  'sigils': 20},
 {'id': 'D079',
  'difficulty': 'Hard',
  'title': '🏆 International Win',
  'description': 'Win 1 Play International match.',
  'sigils': 30},
 {'id': 'D080',
  'difficulty': 'Hard',
  'title': '⚡ Match Marathon',
  'description': 'Complete 5 total matches of any supported game mode.',
  'sigils': 30},
 {'id': 'D081',
  'difficulty': 'Medium',
  'title': '🛒 Level 70 Buy',
  'description': 'Purchase 1 player rated level 70 or above.',
  'sigils': 20},
 {'id': 'D082',
  'difficulty': 'Medium',
  'title': '💎 Level 75 Buy',
  'description': 'Purchase 1 player rated level 75 or above.',
  'sigils': 20},
 {'id': 'D083',
  'difficulty': 'Hard',
  'title': '👑 Level 80 Buy',
  'description': 'Purchase 1 player rated level 80 or above.',
  'sigils': 30},
 {'id': 'D084',
  'difficulty': 'Hard',
  'title': '🔥 Level 85 Buy',
  'description': 'Purchase 1 player rated level 85 or above.',
  'sigils': 30},
 {'id': 'D085',
  'difficulty': 'Medium',
  'title': '💰 Coin Spender',
  'description': 'Spend 25,000 Coins through valid transactions.',
  'sigils': 20},
 {'id': 'D086',
  'difficulty': 'Hard',
  'title': '💥 Coin Burner',
  'description': 'Spend 50,000 Coins through valid transactions.',
  'sigils': 30},
 {'id': 'D087',
  'difficulty': 'Hard',
  'title': '💎 Ruby Spender',
  'description': 'Spend 5 Rubies through valid transactions.',
  'sigils': 30},
 {'id': 'D088',
  'difficulty': 'Medium',
  'title': '💳 Player Shopper',
  'description': 'Purchase 2 players through valid transactions.',
  'sigils': 20},
 {'id': 'D089',
  'difficulty': 'Hard',
  'title': '🏦 Upgrade Investor',
  'description': 'Apply 2 valid player upgrades.',
  'sigils': 30},
 {'id': 'D090',
  'difficulty': 'Medium',
  'title': '🎒 Loadout Shift',
  'description': 'Make 2 valid loadout changes.',
  'sigils': 20},
 {'id': 'D091',
  'difficulty': 'Easy',
  'title': '🎁 Claim Five',
  'description': 'Use /claim successfully at least 5 times during the day.',
  'sigils': 10},
 {'id': 'D092',
  'difficulty': 'Medium',
  'title': '🔥 Claim Streak',
  'description': 'Use /claim on 5 consecutive eligible days.',
  'sigils': 20},
 {'id': 'D093',
  'difficulty': 'Medium',
  'title': '📅 Daily Streak',
  'description': 'Maintain the daily reward streak for 3 consecutive days.',
  'sigils': 20},
 {'id': 'D094',
  'difficulty': 'Hard',
  'title': '⚡ Quest Streak',
  'description': 'Complete at least 1 Daily Mission on 3 consecutive days.',
  'sigils': 30},
 {'id': 'D095',
  'difficulty': 'Medium',
  'title': '🏏 Card Collector',
  'description': 'View 5 different player cards.',
  'sigils': 20},
 {'id': 'D096',
  'difficulty': 'Medium',
  'title': '📊 Stat Reader',
  'description': 'Review 5 match statistics.',
  'sigils': 20},
 {'id': 'D097',
  'difficulty': 'Medium',
  'title': '🔨 Auction Hunter',
  'description': 'Join 2 valid auctions.',
  'sigils': 20},
 {'id': 'D098',
  'difficulty': 'Hard',
  'title': '🏆 Tournament Drive',
  'description': 'Complete 2 tournament matches.',
  'sigils': 30},
 {'id': 'D099',
  'difficulty': 'Medium',
  'title': '👥 Squad Builder',
  'description': 'Confirm 2 valid Playing XIs.',
  'sigils': 20},
 {'id': 'D100',
  'difficulty': 'Hard',
  'title': '🌟 Daily Finisher',
  'description': 'Complete any 5 active Daily Missions before the period ends.',
  'sigils': 30},
 {'id': 'W001',
  'difficulty': 'Easy',
  'title': '🏏 Weekly Run Forge',
  'description': 'Score 300 total team runs across the week.',
  'sigils': 50},
 {'id': 'W002',
  'difficulty': 'Easy',
  'title': '🏏 Weekly Run Engine',
  'description': 'Score 500 total team runs across the week.',
  'sigils': 50},
 {'id': 'W003',
  'difficulty': 'Medium',
  'title': '🔥 Weekly Run Surge',
  'description': 'Score 750 total team runs across the week.',
  'sigils': 80},
 {'id': 'W004',
  'difficulty': 'Medium',
  'title': '💥 Run Stronghold',
  'description': 'Score 1,000 total team runs across the week.',
  'sigils': 80},
 {'id': 'W005',
  'difficulty': 'Hard',
  'title': '⚡ Run Dominion',
  'description': 'Score 1,500 total team runs across the week.',
  'sigils': 120},
 {'id': 'W006',
  'difficulty': 'Hard',
  'title': '👑 Run Empire',
  'description': 'Score 2,000 total team runs across the week.',
  'sigils': 120},
 {'id': 'W007',
  'difficulty': 'Hard',
  'title': '🚀 Run Colossus',
  'description': 'Score 2,500 total team runs across the week.',
  'sigils': 120},
 {'id': 'W008',
  'difficulty': 'Medium',
  'title': '🎯 All-Pitch Runs',
  'description': 'Score 750 team runs with results valid on any pitch condition.',
  'sigils': 80},
 {'id': 'W009',
  'difficulty': 'Hard',
  'title': '🔥 Multi-Match Surge',
  'description': 'Score 1,000 runs across at least five matches.',
  'sigils': 120},
 {'id': 'W010',
  'difficulty': 'Hard',
  'title': '👑 Thousand Week',
  'description': 'Score 1,000+ runs before the weekly period closes.',
  'sigils': 120},
 {'id': 'W011',
  'difficulty': 'Easy',
  'title': '🏏 Player Runstream',
  'description': 'Any one player reaches 200 combined runs during the week.',
  'sigils': 50},
 {'id': 'W012',
  'difficulty': 'Medium',
  'title': '🔥 Player Run Vault',
  'description': 'Any one player reaches 300 combined runs during the week.',
  'sigils': 80},
 {'id': 'W013',
  'difficulty': 'Medium',
  'title': '💥 Player Run Tower',
  'description': 'Any one player reaches 500 combined runs during the week.',
  'sigils': 80},
 {'id': 'W014',
  'difficulty': 'Hard',
  'title': '⚡ Player Run Crown',
  'description': 'Any one player reaches 700 combined runs during the week.',
  'sigils': 120},
 {'id': 'W015',
  'difficulty': 'Hard',
  'title': '👑 Player Run Legend',
  'description': 'Any one player reaches 1,000 combined runs during the week.',
  'sigils': 120},
 {'id': 'W016',
  'difficulty': 'Medium',
  'title': '🎯 Chase Runstream',
  'description': 'Any one player reaches 200 combined chase runs.',
  'sigils': 80},
 {'id': 'W017',
  'difficulty': 'Hard',
  'title': '🔥 Chase Run Vault',
  'description': 'Any one player reaches 400 combined chase runs.',
  'sigils': 120},
 {'id': 'W018',
  'difficulty': 'Hard',
  'title': '💯 Weekly Century',
  'description': 'Any player scores a century in a match during the week.',
  'sigils': 120},
 {'id': 'W019',
  'difficulty': 'Medium',
  'title': '🛡️ Defence Fifty',
  'description': 'Any player scores 50 while defending during the week.',
  'sigils': 80},
 {'id': 'W020',
  'difficulty': 'Hard',
  'title': '👑 Defence Century',
  'description': 'Any player scores 100 while defending during the week.',
  'sigils': 120},
 {'id': 'W021',
  'difficulty': 'Easy',
  'title': '🔥 Four Hunter',
  'description': 'Hit 15 fours across the week.',
  'sigils': 50},
 {'id': 'W022',
  'difficulty': 'Medium',
  'title': '💥 Four Machine',
  'description': 'Hit 30 fours across the week.',
  'sigils': 80},
 {'id': 'W023',
  'difficulty': 'Hard',
  'title': '⚡ Boundary Storm',
  'description': 'Hit 50 fours across the week.',
  'sigils': 120},
 {'id': 'W024',
  'difficulty': 'Easy',
  'title': '🔥 Six Forge',
  'description': 'Hit 10 sixes across the week.',
  'sigils': 50},
 {'id': 'W025',
  'difficulty': 'Medium',
  'title': '💥 Sixes Hitting Machine',
  'description': 'Hit 20 sixes across the week.',
  'sigils': 80},
 {'id': 'W026',
  'difficulty': 'Hard',
  'title': '👑 Sixes Factory',
  'description': 'Hit 40 sixes across the week.',
  'sigils': 120},
 {'id': 'W027',
  'difficulty': 'Hard',
  'title': '🚀 Sixes Empire',
  'description': 'Hit 60 sixes across the week.',
  'sigils': 120},
 {'id': 'W028',
  'difficulty': 'Medium',
  'title': '🎯 Player Six Burst',
  'description': 'Have one player hit 4 sixes in a single match.',
  'sigils': 80},
 {'id': 'W029',
  'difficulty': 'Hard',
  'title': '🔥 Player Six Storm',
  'description': 'Have one player hit 6 sixes in a single match.',
  'sigils': 120},
 {'id': 'W030',
  'difficulty': 'Hard',
  'title': '⚡ Chase Six Storm',
  'description': 'Hit 25 sixes while chasing across the week.',
  'sigils': 120},
 {'id': 'W031',
  'difficulty': 'Easy',
  'title': '🎯 Wicket Hunter',
  'description': 'Take 5 wickets across the week.',
  'sigils': 50},
 {'id': 'W032',
  'difficulty': 'Medium',
  'title': '🔥 Wicket Forge',
  'description': 'Take 10 wickets across the week.',
  'sigils': 80},
 {'id': 'W033',
  'difficulty': 'Medium',
  'title': '💥 Wicket Bank',
  'description': 'Take 20 wickets across the week.',
  'sigils': 80},
 {'id': 'W034',
  'difficulty': 'Hard',
  'title': '👑 Wicket Dominion',
  'description': 'Take 30 wickets across the week.',
  'sigils': 120},
 {'id': 'W035',
  'difficulty': 'Hard',
  'title': '🚀 Wicket Empire',
  'description': 'Take 50 wickets across the week.',
  'sigils': 120},
 {'id': 'W036',
  'difficulty': 'Medium',
  'title': '🎯 Three-Wicket Burst',
  'description': 'Have one player take 3 wickets in a match.',
  'sigils': 80},
 {'id': 'W037',
  'difficulty': 'Hard',
  'title': '🔥 Five-Wicket Master',
  'description': 'Have one player take 5 wickets in a match.',
  'sigils': 120},
 {'id': 'W038',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Hunter',
  'description': 'Take 5 powerplay wickets across the week.',
  'sigils': 80},
 {'id': 'W039',
  'difficulty': 'Medium',
  'title': '💥 Middle Over Snare',
  'description': 'Take 5 middle-over wickets across the week.',
  'sigils': 80},
 {'id': 'W040',
  'difficulty': 'Hard',
  'title': '👑 Death Over Hunter',
  'description': 'Take 8 death-over wickets across the week.',
  'sigils': 120},
 {'id': 'W041',
  'difficulty': 'Easy',
  'title': '🟢 Dot Maker',
  'description': 'Deliver 30 dot balls across the week.',
  'sigils': 50},
 {'id': 'W042',
  'difficulty': 'Medium',
  'title': '🎯 Dot Storm',
  'description': 'Deliver 60 dot balls across the week.',
  'sigils': 80},
 {'id': 'W043',
  'difficulty': 'Hard',
  'title': '🔥 Dot Dominion',
  'description': 'Deliver 100 dot balls across the week.',
  'sigils': 120},
 {'id': 'W044',
  'difficulty': 'Medium',
  'title': '🧊 Powerplay Lock',
  'description': 'Complete 3 powerplay overs conceding 7 or fewer each.',
  'sigils': 80},
 {'id': 'W045',
  'difficulty': 'Hard',
  'title': '🛡️ Middle Over Lock',
  'description': 'Complete 3 middle overs conceding 7 or fewer each.',
  'sigils': 120},
 {'id': 'W046',
  'difficulty': 'Hard',
  'title': '🔥 Death Over Lock',
  'description': 'Complete 3 death overs conceding 9 or fewer each.',
  'sigils': 120},
 {'id': 'W047',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Runner',
  'description': 'Score 75 team runs in powerplay overs.',
  'sigils': 80},
 {'id': 'W048',
  'difficulty': 'Medium',
  'title': '🔥 Middle Over Runner',
  'description': 'Score 100 team runs in middle overs.',
  'sigils': 80},
 {'id': 'W049',
  'difficulty': 'Hard',
  'title': '💥 Death Over Runner',
  'description': 'Score 100 team runs in death overs.',
  'sigils': 120},
 {'id': 'W050',
  'difficulty': 'Hard',
  'title': '👑 Death Over Burst',
  'description': 'Score 150 team runs in death overs.',
  'sigils': 120},
 {'id': 'W051',
  'difficulty': 'Easy',
  'title': '🏃 Chase Starter',
  'description': 'Win 3 matches while chasing.',
  'sigils': 50},
 {'id': 'W052',
  'difficulty': 'Medium',
  'title': '🔥 Chase Master',
  'description': 'Win 5 matches while chasing.',
  'sigils': 80},
 {'id': 'W053',
  'difficulty': 'Hard',
  'title': '👑 Chase King',
  'description': 'Win 7 matches while chasing.',
  'sigils': 120},
 {'id': 'W054',
  'difficulty': 'Hard',
  'title': '⚡ Late Chase Master',
  'description': 'Win 2 chases after reaching the final five overs.',
  'sigils': 120},
 {'id': 'W055',
  'difficulty': 'Medium',
  'title': '🎯 Chase Run Vault',
  'description': 'Score 500 team runs while chasing across matches.',
  'sigils': 80},
 {'id': 'W056',
  'difficulty': 'Hard',
  'title': '💯 Chase Century Win',
  'description': 'Have a player score 100 while chasing and win that match.',
  'sigils': 120},
 {'id': 'W057',
  'difficulty': 'Hard',
  'title': '🔥 Chase Fifty Win',
  'description': 'Have a player score 50 while chasing and win that match twice.',
  'sigils': 120},
 {'id': 'W058',
  'difficulty': 'Easy',
  'title': '🛡️ Defence Starter',
  'description': 'Win 3 matches while defending.',
  'sigils': 50},
 {'id': 'W059',
  'difficulty': 'Medium',
  'title': '🔥 Defence Master',
  'description': 'Win 5 matches while defending.',
  'sigils': 80},
 {'id': 'W060',
  'difficulty': 'Hard',
  'title': '👑 Defence King',
  'description': 'Win 7 matches while defending.',
  'sigils': 120},
 {'id': 'W061',
  'difficulty': 'Hard',
  'title': '⚡ Defence Wicket Storm',
  'description': 'Take 10 wickets while defending across matches.',
  'sigils': 120},
 {'id': 'W062',
  'difficulty': 'Hard',
  'title': '🔥 Defence Five',
  'description': 'Take 5 wickets while defending in a single match.',
  'sigils': 120},
 {'id': 'W063',
  'difficulty': 'Medium',
  'title': '🎯 Comeback Chase',
  'description': 'Win 2 chases after trailing at some point.',
  'sigils': 80},
 {'id': 'W064',
  'difficulty': 'Medium',
  'title': '🛡️ Comeback Defence',
  'description': 'Win 2 defended matches after conceding a boundary.',
  'sigils': 80},
 {'id': 'W065',
  'difficulty': 'Medium',
  'title': '🏏 Match Circuit',
  'description': 'Complete 7 total Play Game matches during the week.',
  'sigils': 80},
 {'id': 'W066',
  'difficulty': 'Medium',
  'title': '🔥 IPL Circuit',
  'description': 'Complete 3 Play IPL matches during the week.',
  'sigils': 80},
 {'id': 'W067',
  'difficulty': 'Hard',
  'title': '👑 IPL Win Run',
  'description': 'Win 3 Play IPL matches during the week.',
  'sigils': 120},
 {'id': 'W068',
  'difficulty': 'Medium',
  'title': '🌍 International Circuit',
  'description': 'Complete 3 Play International matches during the week.',
  'sigils': 80},
 {'id': 'W069',
  'difficulty': 'Hard',
  'title': '🏆 International Win Run',
  'description': 'Win 3 Play International matches during the week.',
  'sigils': 120},
 {'id': 'W070',
  'difficulty': 'Hard',
  'title': '⚡ Weekly Marathon',
  'description': 'Complete 12 total matches across supported modes.',
  'sigils': 120},
 {'id': 'W071',
  'difficulty': 'Medium',
  'title': '🛒 Level 70 Collector',
  'description': 'Purchase 5 players rated level 70 or above.',
  'sigils': 80},
 {'id': 'W072',
  'difficulty': 'Medium',
  'title': '💎 Level 75 Collector',
  'description': 'Purchase 3 players rated level 75 or above.',
  'sigils': 80},
 {'id': 'W073',
  'difficulty': 'Hard',
  'title': '👑 Level 80 Collector',
  'description': 'Purchase 2 players rated level 80 or above.',
  'sigils': 120},
 {'id': 'W074',
  'difficulty': 'Hard',
  'title': '🔥 Level 85 Collector',
  'description': 'Purchase 1 player rated level 85 or above.',
  'sigils': 120},
 {'id': 'W075',
  'difficulty': 'Hard',
  'title': '🛒 Ten Player Week',
  'description': 'Purchase 10 players through valid transactions.',
  'sigils': 120},
 {'id': 'W076',
  'difficulty': 'Medium',
  'title': '💰 Coin Spender',
  'description': 'Spend 100,000 Coins through valid transactions.',
  'sigils': 80},
 {'id': 'W077',
  'difficulty': 'Hard',
  'title': '💥 Coin Burner',
  'description': 'Spend 250,000 Coins through valid transactions.',
  'sigils': 120},
 {'id': 'W078',
  'difficulty': 'Medium',
  'title': '💎 Ruby Spender',
  'description': 'Spend 10 Rubies through valid transactions.',
  'sigils': 80},
 {'id': 'W079',
  'difficulty': 'Hard',
  'title': '🏦 Upgrade Investor',
  'description': 'Apply 8 valid player upgrades.',
  'sigils': 120},
 {'id': 'W080',
  'difficulty': 'Medium',
  'title': '🎒 Loadout Shift',
  'description': 'Make 6 valid loadout changes.',
  'sigils': 80},
 {'id': 'W081',
  'difficulty': 'Easy',
  'title': '🎁 Claim Fifteen',
  'description': 'Use /claim successfully at least 15 times during the week.',
  'sigils': 50},
 {'id': 'W082',
  'difficulty': 'Easy',
  'title': '🎁 Claim Flow',
  'description': 'Claim the daily reward on 7 consecutive eligible days.',
  'sigils': 50},
 {'id': 'W083',
  'difficulty': 'Medium',
  'title': '🔥 Daily Streak',
  'description': 'Maintain the daily reward streak for 7 consecutive days.',
  'sigils': 80},
 {'id': 'W084',
  'difficulty': 'Hard',
  'title': '⚡ Quest Week Streak',
  'description': 'Complete at least 1 Daily Mission on all 7 days.',
  'sigils': 120},
 {'id': 'W085',
  'difficulty': 'Hard',
  'title': '👑 Full Week Clear',
  'description': 'Complete all assigned Daily Missions on 7 consecutive days.',
  'sigils': 120},
 {'id': 'W086',
  'difficulty': 'Medium',
  'title': '🏆 Tournament Drive',
  'description': 'Complete 5 tournament matches during the week.',
  'sigils': 80},
 {'id': 'W087',
  'difficulty': 'Hard',
  'title': '🔨 Auction Hunter',
  'description': 'Join 5 valid auctions.',
  'sigils': 120},
 {'id': 'W088',
  'difficulty': 'Hard',
  'title': '💥 Auction Winner',
  'description': 'Win 3 valid auction bids.',
  'sigils': 120},
 {'id': 'W089',
  'difficulty': 'Medium',
  'title': '🌟 Card Collector',
  'description': 'View 15 different player cards.',
  'sigils': 80},
 {'id': 'W090',
  'difficulty': 'Medium',
  'title': '📊 Stat Reader',
  'description': 'Review 15 match statistics.',
  'sigils': 80},
 {'id': 'W091',
  'difficulty': 'Medium',
  'title': '👥 Squad Builder',
  'description': 'Confirm 5 valid Playing XIs.',
  'sigils': 80},
 {'id': 'W092',
  'difficulty': 'Hard',
  'title': '🧮 Overseas Keeper',
  'description': 'Confirm 3 XIs while satisfying the overseas-player limit.',
  'sigils': 120},
 {'id': 'W093',
  'difficulty': 'Medium',
  'title': '🔄 Team Shaper',
  'description': 'Make 6 valid team updates.',
  'sigils': 80},
 {'id': 'W094',
  'difficulty': 'Hard',
  'title': '🎒 Loadout Master',
  'description': 'Equip 3 different valid loadouts.',
  'sigils': 120},
 {'id': 'W095',
  'difficulty': 'Medium',
  'title': '🎁 Pack Opener',
  'description': 'Open 5 packs during the week.',
  'sigils': 80},
 {'id': 'W096',
  'difficulty': 'Hard',
  'title': '💎 Pack Buyer',
  'description': 'Purchase 5 packs during the week.',
  'sigils': 120},
 {'id': 'W097',
  'difficulty': 'Medium',
  'title': '⚔️ Quest Runner',
  'description': 'Complete 15 Weekly-eligible quest events from supported systems.',
  'sigils': 80},
 {'id': 'W098',
  'difficulty': 'Hard',
  'title': '🏆 Weekly Winner',
  'description': 'Win 10 total matches across all supported modes.',
  'sigils': 120},
 {'id': 'W099',
  'difficulty': 'Hard',
  'title': '🔥 Weekly Finish',
  'description': 'Complete at least 5 active Weekly Missions.',
  'sigils': 120},
 {'id': 'W100',
  'difficulty': 'Hard',
  'title': '👑 Week Complete',
  'description': 'Complete all active Weekly Missions before the weekly period closes.',
  'sigils': 120},
 {'id': 'M001',
  'difficulty': 'Easy',
  'title': '🏏 Monthly Run Forge',
  'description': 'Score 500 total team runs across the month.',
  'sigils': 100},
 {'id': 'M002',
  'difficulty': 'Easy',
  'title': '🏏 Monthly Run Engine',
  'description': 'Score 750 total team runs across the month.',
  'sigils': 100},
 {'id': 'M003',
  'difficulty': 'Medium',
  'title': '🔥 Monthly Run Surge',
  'description': 'Score 1,000 total team runs across the month.',
  'sigils': 150},
 {'id': 'M004',
  'difficulty': 'Medium',
  'title': '💥 Run Stronghold',
  'description': 'Score 1,500 total team runs across the month.',
  'sigils': 150},
 {'id': 'M005',
  'difficulty': 'Hard',
  'title': '⚡ Run Dominion',
  'description': 'Score 2,000 total team runs across the month.',
  'sigils': 200},
 {'id': 'M006',
  'difficulty': 'Hard',
  'title': '👑 Run Empire',
  'description': 'Score 3,000 total team runs across the month.',
  'sigils': 200},
 {'id': 'M007',
  'difficulty': 'Hard',
  'title': '🚀 Run Colossus',
  'description': 'Score 5,000 total team runs across the month.',
  'sigils': 200},
 {'id': 'M008',
  'difficulty': 'Hard',
  'title': '🌟 Five-K Run Club',
  'description': 'Score 5,000 combined team runs before month end.',
  'sigils': 200},
 {'id': 'M009',
  'difficulty': 'Medium',
  'title': '🎯 All-Pitch Runner',
  'description': 'Score 1,000 team runs regardless of pitch condition.',
  'sigils': 150},
 {'id': 'M010',
  'difficulty': 'Hard',
  'title': '🔥 Multi-Match Marathon',
  'description': 'Score 2,000 runs across at least 15 matches.',
  'sigils': 200},
 {'id': 'M011',
  'difficulty': 'Easy',
  'title': '🏏 Player Runstream',
  'description': 'Any one player reaches 300 combined runs during the month.',
  'sigils': 100},
 {'id': 'M012',
  'difficulty': 'Medium',
  'title': '🔥 Player Run Vault',
  'description': 'Any one player reaches 500 combined runs during the month.',
  'sigils': 150},
 {'id': 'M013',
  'difficulty': 'Medium',
  'title': '💥 Player Run Tower',
  'description': 'Any one player reaches 700 combined runs during the month.',
  'sigils': 150},
 {'id': 'M014',
  'difficulty': 'Hard',
  'title': '⚡ Player Run Crown',
  'description': 'Any one player reaches 1,000 combined runs during the month.',
  'sigils': 200},
 {'id': 'M015',
  'difficulty': 'Hard',
  'title': '👑 Player Run Legend',
  'description': 'Any one player reaches 1,500 combined runs during the month.',
  'sigils': 200},
 {'id': 'M016',
  'difficulty': 'Medium',
  'title': '🎯 Chase Runstream',
  'description': 'Any one player reaches 300 combined chase runs.',
  'sigils': 150},
 {'id': 'M017',
  'difficulty': 'Hard',
  'title': '🔥 Chase Run Vault',
  'description': 'Any one player reaches 500 combined chase runs.',
  'sigils': 200},
 {'id': 'M018',
  'difficulty': 'Hard',
  'title': '💯 Century Month',
  'description': 'Have players produce 3 centuries during the month.',
  'sigils': 200},
 {'id': 'M019',
  'difficulty': 'Medium',
  'title': '🛡️ Defence Fifty',
  'description': 'Have players produce 3 fifties while defending.',
  'sigils': 150},
 {'id': 'M020',
  'difficulty': 'Hard',
  'title': '👑 Defence Century',
  'description': 'Have players produce 2 centuries while defending.',
  'sigils': 200},
 {'id': 'M021',
  'difficulty': 'Easy',
  'title': '🔥 Four Hunter',
  'description': 'Hit 30 fours across the month.',
  'sigils': 100},
 {'id': 'M022',
  'difficulty': 'Medium',
  'title': '💥 Four Machine',
  'description': 'Hit 60 fours across the month.',
  'sigils': 150},
 {'id': 'M023',
  'difficulty': 'Hard',
  'title': '⚡ Boundary Storm',
  'description': 'Hit 100 fours across the month.',
  'sigils': 200},
 {'id': 'M024',
  'difficulty': 'Easy',
  'title': '🔥 Six Forge',
  'description': 'Hit 20 sixes across the month.',
  'sigils': 100},
 {'id': 'M025',
  'difficulty': 'Medium',
  'title': '💥 Sixes Hitting Machine',
  'description': 'Hit 50 sixes across the month.',
  'sigils': 150},
 {'id': 'M026',
  'difficulty': 'Hard',
  'title': '👑 Sixes Factory',
  'description': 'Hit 75 sixes across the month.',
  'sigils': 200},
 {'id': 'M027',
  'difficulty': 'Hard',
  'title': '🚀 Sixes Empire',
  'description': 'Hit 100 sixes across the month.',
  'sigils': 200},
 {'id': 'M028',
  'difficulty': 'Hard',
  'title': '🌟 Sixes Colossus',
  'description': 'Hit 150 sixes across the month.',
  'sigils': 200},
 {'id': 'M029',
  'difficulty': 'Hard',
  'title': '🎯 Player Six Storm',
  'description': 'Have one player hit 6 sixes in a single match.',
  'sigils': 200},
 {'id': 'M030',
  'difficulty': 'Hard',
  'title': '🔥 Player Six Factory',
  'description': 'Have one player hit 8 sixes in a single match.',
  'sigils': 200},
 {'id': 'M031',
  'difficulty': 'Easy',
  'title': '🎯 Wicket Hunter',
  'description': 'Take 10 wickets across the month.',
  'sigils': 100},
 {'id': 'M032',
  'difficulty': 'Medium',
  'title': '🔥 Wicket Forge',
  'description': 'Take 20 wickets across the month.',
  'sigils': 150},
 {'id': 'M033',
  'difficulty': 'Medium',
  'title': '💥 Wicket Bank',
  'description': 'Take 30 wickets across the month.',
  'sigils': 150},
 {'id': 'M034',
  'difficulty': 'Hard',
  'title': '👑 Wicket Dominion',
  'description': 'Take 50 wickets across the month.',
  'sigils': 200},
 {'id': 'M035',
  'difficulty': 'Hard',
  'title': '🚀 Wicket Empire',
  'description': 'Take 75 wickets across the month.',
  'sigils': 200},
 {'id': 'M036',
  'difficulty': 'Medium',
  'title': '🎯 Three-Wicket Burst',
  'description': 'Have one player take 3 wickets in a match.',
  'sigils': 150},
 {'id': 'M037',
  'difficulty': 'Hard',
  'title': '🔥 Five-Wicket Master',
  'description': 'Have one player take 5 wickets in a match.',
  'sigils': 200},
 {'id': 'M038',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Hunter',
  'description': 'Take 10 powerplay wickets across the month.',
  'sigils': 150},
 {'id': 'M039',
  'difficulty': 'Medium',
  'title': '💥 Middle Over Snare',
  'description': 'Take 10 middle-over wickets across the month.',
  'sigils': 150},
 {'id': 'M040',
  'difficulty': 'Hard',
  'title': '👑 Death Over Hunter',
  'description': 'Take 15 death-over wickets across the month.',
  'sigils': 200},
 {'id': 'M041',
  'difficulty': 'Easy',
  'title': '🟢 Dot Maker',
  'description': 'Deliver 60 dot balls across the month.',
  'sigils': 100},
 {'id': 'M042',
  'difficulty': 'Medium',
  'title': '🎯 Dot Storm',
  'description': 'Deliver 120 dot balls across the month.',
  'sigils': 150},
 {'id': 'M043',
  'difficulty': 'Hard',
  'title': '🔥 Dot Dominion',
  'description': 'Deliver 200 dot balls across the month.',
  'sigils': 200},
 {'id': 'M044',
  'difficulty': 'Medium',
  'title': '🧊 Powerplay Lock',
  'description': 'Complete 8 powerplay overs conceding 7 or fewer each.',
  'sigils': 150},
 {'id': 'M045',
  'difficulty': 'Hard',
  'title': '🛡️ Middle Over Lock',
  'description': 'Complete 8 middle overs conceding 7 or fewer each.',
  'sigils': 200},
 {'id': 'M046',
  'difficulty': 'Hard',
  'title': '🔥 Death Over Lock',
  'description': 'Complete 8 death overs conceding 9 or fewer each.',
  'sigils': 200},
 {'id': 'M047',
  'difficulty': 'Medium',
  'title': '⚡ Powerplay Runner',
  'description': 'Score 200 team runs in powerplay overs.',
  'sigils': 150},
 {'id': 'M048',
  'difficulty': 'Medium',
  'title': '🔥 Middle Over Runner',
  'description': 'Score 300 team runs in middle overs.',
  'sigils': 150},
 {'id': 'M049',
  'difficulty': 'Hard',
  'title': '💥 Death Over Runner',
  'description': 'Score 300 team runs in death overs.',
  'sigils': 200},
 {'id': 'M050',
  'difficulty': 'Hard',
  'title': '👑 Death Over Burst',
  'description': 'Score 500 team runs in death overs.',
  'sigils': 200},
 {'id': 'M051',
  'difficulty': 'Easy',
  'title': '🏃 Chase Starter',
  'description': 'Win 5 matches while chasing.',
  'sigils': 100},
 {'id': 'M052',
  'difficulty': 'Medium',
  'title': '🔥 Chase Master',
  'description': 'Win 10 matches while chasing.',
  'sigils': 150},
 {'id': 'M053',
  'difficulty': 'Hard',
  'title': '👑 Chase King',
  'description': 'Win 15 matches while chasing.',
  'sigils': 200},
 {'id': 'M054',
  'difficulty': 'Hard',
  'title': '⚡ Late Chase Master',
  'description': 'Win 5 chases after reaching the final five overs.',
  'sigils': 200},
 {'id': 'M055',
  'difficulty': 'Medium',
  'title': '🎯 Chase Run Vault',
  'description': 'Score 1,000 team runs while chasing across matches.',
  'sigils': 150},
 {'id': 'M056',
  'difficulty': 'Hard',
  'title': '💯 Chase Century Win',
  'description': 'Have a player score 100 while chasing and win that match 3 times.',
  'sigils': 200},
 {'id': 'M057',
  'difficulty': 'Hard',
  'title': '🔥 Chase Fifty Win',
  'description': 'Have a player score 50 while chasing and win that match 5 times.',
  'sigils': 200},
 {'id': 'M058',
  'difficulty': 'Easy',
  'title': '🛡️ Defence Starter',
  'description': 'Win 5 matches while defending.',
  'sigils': 100},
 {'id': 'M059',
  'difficulty': 'Medium',
  'title': '🔥 Defence Master',
  'description': 'Win 10 matches while defending.',
  'sigils': 150},
 {'id': 'M060',
  'difficulty': 'Hard',
  'title': '👑 Defence King',
  'description': 'Win 15 matches while defending.',
  'sigils': 200},
 {'id': 'M061',
  'difficulty': 'Hard',
  'title': '⚡ Defence Wicket Storm',
  'description': 'Take 25 wickets while defending across matches.',
  'sigils': 200},
 {'id': 'M062',
  'difficulty': 'Hard',
  'title': '🔥 Defence Five',
  'description': 'Take 5 wickets while defending in a single match.',
  'sigils': 200},
 {'id': 'M063',
  'difficulty': 'Medium',
  'title': '🎯 Comeback Chase',
  'description': 'Win 5 chases after trailing at some point.',
  'sigils': 150},
 {'id': 'M064',
  'difficulty': 'Medium',
  'title': '🛡️ Comeback Defence',
  'description': 'Win 5 defended matches after conceding a boundary.',
  'sigils': 150},
 {'id': 'M065',
  'difficulty': 'Medium',
  'title': '🏏 Match Circuit',
  'description': 'Complete 15 total Play Game matches during the month.',
  'sigils': 150},
 {'id': 'M066',
  'difficulty': 'Medium',
  'title': '🔥 IPL Circuit',
  'description': 'Complete 10 Play IPL matches during the month.',
  'sigils': 150},
 {'id': 'M067',
  'difficulty': 'Hard',
  'title': '👑 IPL Win Run',
  'description': 'Win 7 Play IPL matches during the month.',
  'sigils': 200},
 {'id': 'M068',
  'difficulty': 'Medium',
  'title': '🌍 International Circuit',
  'description': 'Complete 10 Play International matches during the month.',
  'sigils': 150},
 {'id': 'M069',
  'difficulty': 'Hard',
  'title': '🏆 International Win Run',
  'description': 'Win 7 Play International matches during the month.',
  'sigils': 200},
 {'id': 'M070',
  'difficulty': 'Hard',
  'title': '⚡ Match Marathon',
  'description': 'Complete 30 total matches across supported modes.',
  'sigils': 200},
 {'id': 'M071',
  'difficulty': 'Medium',
  'title': '🛒 Level 70 Collector',
  'description': 'Purchase 10 players rated level 70 or above.',
  'sigils': 150},
 {'id': 'M072',
  'difficulty': 'Medium',
  'title': '💎 Level 75 Collector',
  'description': 'Purchase 5 players rated level 75 or above.',
  'sigils': 150},
 {'id': 'M073',
  'difficulty': 'Hard',
  'title': '👑 Level 80 Collector',
  'description': 'Purchase 3 players rated level 80 or above.',
  'sigils': 200},
 {'id': 'M074',
  'difficulty': 'Hard',
  'title': '🔥 Level 85 Collector',
  'description': 'Purchase 2 players rated level 85 or above.',
  'sigils': 200},
 {'id': 'M075',
  'difficulty': 'Hard',
  'title': '🛒 Twenty Player Month',
  'description': 'Purchase 20 players through valid transactions.',
  'sigils': 200},
 {'id': 'M076',
  'difficulty': 'Medium',
  'title': '💰 Coin Spender',
  'description': 'Spend 250,000 Coins through valid transactions.',
  'sigils': 150},
 {'id': 'M077',
  'difficulty': 'Hard',
  'title': '💥 Coin Burner',
  'description': 'Spend 500,000 Coins through valid transactions.',
  'sigils': 200},
 {'id': 'M078',
  'difficulty': 'Medium',
  'title': '💎 Ruby Spender',
  'description': 'Spend 25 Rubies through valid transactions.',
  'sigils': 150},
 {'id': 'M079',
  'difficulty': 'Hard',
  'title': '🏦 Upgrade Investor',
  'description': 'Apply 20 valid player upgrades.',
  'sigils': 200},
 {'id': 'M080',
  'difficulty': 'Medium',
  'title': '🎒 Loadout Architect',
  'description': 'Make 15 valid loadout changes.',
  'sigils': 150},
 {'id': 'M081',
  'difficulty': 'Easy',
  'title': '🎁 Claim Forty',
  'description': 'Use /claim successfully at least 40 times during the month.',
  'sigils': 100},
 {'id': 'M082',
  'difficulty': 'Medium',
  'title': '🎁 Claim Sixty',
  'description': 'Use /claim successfully at least 60 times during the month.',
  'sigils': 150},
 {'id': 'M083',
  'difficulty': 'Medium',
  'title': '🔥 Daily Streak',
  'description': 'Maintain the daily reward streak for 14 consecutive days.',
  'sigils': 150},
 {'id': 'M084',
  'difficulty': 'Hard',
  'title': '⚡ Month Streak',
  'description': 'Maintain the daily reward streak for 30 consecutive days.',
  'sigils': 200},
 {'id': 'M085',
  'difficulty': 'Hard',
  'title': '👑 Quest Streak Month',
  'description': 'Complete at least 1 Daily Mission on 30 consecutive days.',
  'sigils': 200},
 {'id': 'M086',
  'difficulty': 'Hard',
  'title': '🏆 Full Month Drive',
  'description': 'Complete at least 1 Weekly Mission in 4 separate weeks.',
  'sigils': 200},
 {'id': 'M087',
  'difficulty': 'Hard',
  'title': '🔨 Auction Hunter',
  'description': 'Join 12 valid auctions.',
  'sigils': 200},
 {'id': 'M088',
  'difficulty': 'Hard',
  'title': '💥 Auction Winner',
  'description': 'Win 8 valid auction bids.',
  'sigils': 200},
 {'id': 'M089',
  'difficulty': 'Medium',
  'title': '🌟 Card Collector',
  'description': 'View 30 different player cards.',
  'sigils': 150},
 {'id': 'M090',
  'difficulty': 'Medium',
  'title': '📊 Stat Reader',
  'description': 'Review 30 match statistics.',
  'sigils': 150},
 {'id': 'M091',
  'difficulty': 'Medium',
  'title': '👥 Squad Builder',
  'description': 'Confirm 12 valid Playing XIs.',
  'sigils': 150},
 {'id': 'M092',
  'difficulty': 'Hard',
  'title': '🧮 Overseas Keeper',
  'description': 'Confirm 6 XIs while satisfying the overseas-player limit.',
  'sigils': 200},
 {'id': 'M093',
  'difficulty': 'Medium',
  'title': '🔄 Team Shaper',
  'description': 'Make 15 valid team updates.',
  'sigils': 150},
 {'id': 'M094',
  'difficulty': 'Hard',
  'title': '🎒 Loadout Master',
  'description': 'Equip 5 different valid loadouts.',
  'sigils': 200},
 {'id': 'M095',
  'difficulty': 'Medium',
  'title': '🎁 Pack Opener',
  'description': 'Open 15 packs during the month.',
  'sigils': 150},
 {'id': 'M096',
  'difficulty': 'Hard',
  'title': '💎 Pack Buyer',
  'description': 'Purchase 10 packs during the month.',
  'sigils': 200},
 {'id': 'M097',
  'difficulty': 'Medium',
  'title': '⚔️ Quest Runner',
  'description': 'Complete 30 supported quest events across the month.',
  'sigils': 150},
 {'id': 'M098',
  'difficulty': 'Hard',
  'title': '🏆 Monthly Winner',
  'description': 'Win 20 total matches across all supported modes.',
  'sigils': 200},
 {'id': 'M099',
  'difficulty': 'Hard',
  'title': '🔥 Monthly Finish',
  'description': 'Complete at least 10 active Monthly Missions.',
  'sigils': 200},
 {'id': 'M100',
  'difficulty': 'Hard',
  'title': '👑 Month Complete',
  'description': 'Complete all active Monthly Missions before the month closes.',
  'sigils': 200}]

TASKS_BY_ID = {task["id"]: task for task in QUEST_TASKS}
TASKS_BY_PERIOD = {
    "daily": [t for t in QUEST_TASKS if t["id"].startswith("D")],
    "weekly": [t for t in QUEST_TASKS if t["id"].startswith("W")],
    "monthly": [t for t in QUEST_TASKS if t["id"].startswith("M")],
}

DIFFICULTY_COUNTS = {
    "daily": {"Easy": 2, "Medium": 2, "Hard": 1},
    "weekly": {"Easy": 2, "Medium": 2, "Hard": 2},
    "monthly": {"Easy": 3, "Medium": 4, "Hard": 3},
}

REWARD_MAP = {
    "daily": {"Easy": {"sigils": 10, "coins": 100, "rubies": 0}, "Medium": {"sigils": 20, "coins": 1500, "rubies": 0}, "Hard": {"sigils": 30, "coins": 2000, "rubies": 0}},
    "weekly": {"Easy": {"sigils": 50, "coins": 2500, "rubies": 0}, "Medium": {"sigils": 80, "coins": 3500, "rubies": 0}, "Hard": {"sigils": 120, "coins": 5000, "rubies": 0}},
    "monthly": {"Easy": {"sigils": 100, "coins": 500, "rubies": 0}, "Medium": {"sigils": 150, "coins": 0, "rubies": 100}, "Hard": {"sigils": 200, "coins": 0, "rubies": 200}},
}

for _task in QUEST_TASKS:
    _period = {"D": "daily", "W": "weekly", "M": "monthly"}[_task["id"][0]]
    _reward = REWARD_MAP[_period][_task["difficulty"]]
    # The supplied PDF controls Sigil amounts. Runtime economy adds Coins/Rubies.
    assert int(_task["sigils"]) == int(_reward["sigils"]), (_task["id"], _task["sigils"], _reward["sigils"])

del _task, _period, _reward
