"""Stadium name pool for the /play match-ready screen."""
from __future__ import annotations

import random

STADIUMS = [
    "Melbourne Cricket Ground",
    "Eden Gardens",
    "Narendra Modi Stadium",
    "Wankhede Stadium",
    "M. A. Chidambaram Stadium",
    "Arun Jaitley Stadium",
    "Sawai Mansingh Stadium",
    "Greenfield International Stadium",
    "Punjab Cricket Association IS Bindra Stadium",
    "Himachal Pradesh Cricket Association Stadium",
    "Rajiv Gandhi International Stadium",
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
    "Saurashtra Cricket Association Stadium",
    "Holkar Cricket Stadium",
    "Vidarbha Cricket Association Stadium",
    "JSCA International Stadium Complex",
    "BRSABV Ekana Cricket Stadium",
    "M. Chinnaswamy Stadium",
    "Pallekele International Cricket Stadium",
    "Galle International Stadium",
    "R. Premadasa Stadium",
    "Sharjah Cricket Stadium",
    "Dubai International Cricket Stadium",
    "Sheikh Zayed Cricket Stadium",
    "The Oval",
    "Lord's Cricket Ground",
    "Old Trafford",
    "Headingley",
    "Trent Bridge",
    "Edgbaston",
    "Rose Bowl",
    "County Ground, Bristol",
    "Sophia Gardens",
    "Basin Reserve",
    "Seddon Park",
    "Eden Park",
    "Adelaide Oval",
    "Perth Stadium",
    "Gabba",
    "Sydney Cricket Ground",
    "Optus Stadium",
    "Bellerive Oval",
    "SuperSport Park",
    "Newlands",
    "Kingsmead",
    "St George's Park",
    "National Stadium, Karachi",
    "Gaddafi Stadium",
    "Rawalpindi Cricket Stadium",
    "Multan Cricket Stadium",
    "Zayed Cricket Stadium",
    "Providence Stadium",
    "Brian Lara Cricket Academy",
    "Sabina Park",
    "Kensington Oval",
]


def random_stadium() -> str:
    return random.choice(STADIUMS)
